// The scale-up measurement spike: cost of a FULL-SECURITY-SHAPED verify in the flattened
// single-contract architecture (generated by tools/gen_fullsize.py). Synthetic values, real
// cost model. Pass --costs to capture the numbers in costs-reports.json.
import { describe, expect, it } from "vitest";

const accounts = simnet.getAccounts();
const deployer = accounts.get("deployer")!;

describe("fullsize -- the scale-up cost-shape measurement", () => {
  it("runs the full-parameter work shape in one call", () => {
    const t0 = performance.now();
    const res = simnet.callReadOnlyFn("fullsize", "run", [], deployer).result;
    const ms = performance.now() - t0;
    console.log(`fullsize run() wall time: ${ms.toFixed(0)}ms`);
    expect(res).toBeDefined();
  });
});
