//! Rust mirror of the tools/params.py parameter points (M2).
//!
//! AUTHORITY: tools/params.py owns the parameter oracle. This file transcribes the raw
//! point fields only; every derived quantity is computed, and main.rs cross-asserts the
//! transcription against the committed export interop/params-full.json, regenerated by:
//!
//!     python3 tools/params.py --json PRODUCTION_POINT > interop/params-full.json
//!
//! A transcription mistake fails the harness (checks R0 through R5), so the Rust
//! constants can never drift silently from the pinned PRODUCTION_POINT.

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Point {
    pub log_trace: u32,
    pub log_blowup: u32,
    pub n_queries: u32,
    pub pow_bits: u32,
    pub air_id: u32,
}

impl Point {
    pub const fn log_domain(&self) -> u32 {
        self.log_trace + self.log_blowup
    }
    pub const fn domain_size(&self) -> usize {
        1usize << self.log_domain()
    }
    pub const fn trace_rows(&self) -> usize {
        1usize << self.log_trace
    }
    /// Fold to a size-2 last layer, transmitted degree-0 final (the toy convention).
    pub const fn n_layers(&self) -> u32 {
        self.log_domain() - 1
    }
    pub const fn blowup(&self) -> u32 {
        1u32 << self.log_blowup
    }
    pub const fn pow_threshold(&self) -> u128 {
        1u128 << (128 - self.pow_bits)
    }
    /// PARAMS = [n_queries, N_LAYERS, BLOWUP, pow_bits] ++ air_id u32 BE (params.py order).
    pub fn params_bytes(&self) -> [u8; 8] {
        let mut out = [0u8; 8];
        out[0] = self.n_queries as u8;
        out[1] = self.n_layers() as u8;
        out[2] = self.blowup() as u8;
        out[3] = self.pow_bits as u8;
        out[4..8].copy_from_slice(&self.air_id.to_be_bytes());
        out
    }
    /// Wire format version byte: the toy point is frozen on v1; every other point is v2
    /// (prover-supplied inverse hints; the verifier checks (t*h) == 1 and multiplies).
    pub fn version(&self) -> u8 {
        if self.log_trace == 3 && self.log_blowup == 1 { 0x01 } else { 0x02 }
    }
}

/// The toy point: 8-row trace, 16-point domain, wire v1. PARAMS must equal the pinned
/// [0x04, 0x03, 0x02, 0x08, 0, 0, 0, 0x0a] (asserted by main.rs check R0).
pub const TOY: Point =
    Point { log_trace: 3, log_blowup: 1, n_queries: 4, pow_bits: 8, air_id: 10 };

/// TRANSCRIBE from the Task 3 pin: run `python3 tools/params.py --json PRODUCTION_POINT`
/// and copy the five raw fields. The values below are CAND_A, the expected winner; if
/// Task 3 pinned a different point, transcribe that point's fields instead. Check R1
/// fails the harness on any mismatch, so a wrong transcription cannot survive.
pub const FULL: Point =
    Point { log_trace: 13, log_blowup: 4, n_queries: 23, pow_bits: 8, air_id: 11 };

/// The additive Fibonacci trace column: t[0] = t[1] = 1, t[k] = t[k-1] + t[k-2] mod p.
pub fn fib_column(rows: usize) -> Vec<u32> {
    let p = (1u64 << 31) - 1;
    let mut t: Vec<u32> = vec![1, 1];
    for k in 2..rows {
        t.push((((t[k - 1] as u64) + (t[k - 2] as u64)) % p) as u32);
    }
    t.truncate(rows);
    t
}

/// Natural canonic-coset row index k to natural circle-domain index i, for a canonic
/// coset of size 2^log_size viewed as its circle domain (half coset, then conjugates):
/// even k sits in the half coset at i = k/2; odd k sits among the conjugates at
/// i = n - (k+1)/2. Verified against Stwo by main.rs check S6 and pinned at the toy
/// point by the prover's TCOL_TOY_PINNED assert (Task 5).
pub fn coset_index_to_domain_index(k: usize, log_size: u32) -> usize {
    let n = 1usize << log_size;
    if k % 2 == 0 {
        k / 2
    } else {
        n - (k + 1) / 2
    }
}
