#!/usr/bin/env python3
"""gen_spec_tables.py: owns every generated block of docs/protocol-spec.md.

Splices deterministic content between HTML-comment fences:
    <!-- BEGIN-GENERATED: <block-id> -->
    <!-- END-GENERATED: <block-id> -->
Refuses to run when any BEGIN lacks its END, an id is unknown, or an id
repeats, listing every offender. Each block's content is read from a
named source (tools/params.py, tools/soundness.py, the production
contracts, tools/kats-full.json, docs/m3-testnet-receipts.md); this file
inlines no protocol value. Deterministic: no timestamps, no env reads.
Run:   python3 tools/gen_spec_tables.py     (regenerates the spec in place)
Tests: python3 tools/test_gen_spec_tables.py
"""
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SPEC = os.path.join(ROOT, "docs", "protocol-spec.md")
FLAT = os.path.join(ROOT, "contracts", "verifold-flat-full-production.clar")
QM31_GEAR = os.path.join(ROOT, "contracts", "full", "qm31.clar")

sys.path.insert(0, HERE)
import params  # noqa: E402

FENCE_RE = re.compile(r"^<!-- (BEGIN|END)-GENERATED: ([a-z0-9][a-z0-9-]*) -->$")


class FenceError(SystemExit):
    pass


def read_text(path):
    with open(path, "r", encoding="utf-8") as f:
        return f.read()


def contract_slice(text, start_anchor, end_anchor):
    """Lines from the unique line containing start_anchor up to but not
    including the first later line containing end_anchor. Asserts the
    start anchor is unique so silent drift is impossible."""
    lines = text.split("\n")
    starts = [i for i, l in enumerate(lines) if start_anchor in l]
    assert len(starts) == 1, (start_anchor, len(starts))
    ends = [i for i, l in enumerate(lines)
            if end_anchor in l and i > starts[0]]
    assert ends, end_anchor
    return "\n".join(lines[starts[0]:ends[0]]).rstrip()


def src_note(*sources):
    return ("<!-- generated by tools/gen_spec_tables.py from: "
            + "; ".join(sources) + " -->")


# ---------------- emitters (Task 1) ----------------

def emit_field_constants():
    p = params.P
    assert p == 2 ** 31 - 1, p
    return "\n".join([
        src_note("tools/params.py (P)"),
        "",
        "| constant | value | definition |",
        "| --- | --- | --- |",
        "| p | {} | the Mersenne prime 2^31 - 1; every base field value"
        " is an integer in [0, p) |".format(p),
    ])


def emit_qm31_tower():
    hdr = read_text(QM31_GEAR)

    def header_line(marker):
        for line in hdr.split("\n"):
            if marker in line:
                assert line.startswith(";;"), line
                # normalize whitespace; drop the gear comment tail after
                # the double-hyphen separator (the spec bans dash prose)
                return " ".join(line[2:].split()).split(" -- ")[0].strip()
        raise AssertionError("qm31.clar header drifted: " + marker)

    return "\n".join([
        src_note("contracts/full/qm31.clar (header: tower polynomials"
                 " and element shape)"),
        "",
        "```text",
        header_line("CM31 = M31[i]"),
        header_line("QM31 = CM31[u]"),
        header_line("An element {c0,c1,c2,c3} means"),
        "```",
    ])


def emit_circle_generator():
    gx, gy = params.G
    assert params.order_is(params.G, 2 ** 31), "G must have order 2^31"
    return "\n".join([
        src_note("tools/params.py (G, order verified via order_is)"),
        "",
        "| constant | value |",
        "| --- | --- |",
        "| G.x | {} |".format(gx),
        "| G.y | {} |".format(gy),
        "| order of G | 2^31, re-verified by params.order_is on every"
        " generation run |",
    ])


def emit_parameter_point():
    pt = params.PRODUCTION_POINT
    d = params.derived(pt)
    free = [("log_trace", pt["log_trace"]), ("log_blowup", pt["log_blowup"]),
            ("n_queries", pt["n_queries"]), ("pow_bits", pt["pow_bits"]),
            ("air_id", pt["air_id"])]
    der = [
        ("LOG_DOMAIN", d["LOG_DOMAIN"]), ("DOMAIN_SIZE", d["DOMAIN_SIZE"]),
        ("N_LAYERS", d["N_LAYERS"]), ("BLOWUP", d["BLOWUP"]),
        ("TRACE_ROWS", d["TRACE_ROWS"]),
        ("OFF", "re {re}, im {im}".format(**d["OFF"])),
        ("H", "re {re}, im {im}".format(**d["H"])),
        ("SX", d["SX"]), ("SY", d["SY"]),
        ("SEL", "A {A}, B {B}, C {C}".format(**d["SEL"])),
        ("B01", "A {A}, B {B}, C {C}".format(**d["B01"])),
        ("POW_THRESHOLD", d["POW_THRESHOLD"]),
        ("PARAMS (8 bytes, hex)", d["PARAMS"].hex()),
    ]
    out = [src_note("tools/params.py (PRODUCTION_POINT, derived())"), "",
           "Free choice tuple (PRODUCTION_POINT):", "",
           "| name | value |", "| --- | --- |"]
    out += ["| {} | {} |".format(k, v) for k, v in free]
    out += ["", "Derived constants at this point:", "",
            "| name | value |", "| --- | --- |"]
    out += ["| {} | {} |".format(k, v) for k, v in der]
    return "\n".join(out)


EMITTERS = {
    "field-constants": emit_field_constants,
    "qm31-tower": emit_qm31_tower,
    "circle-generator": emit_circle_generator,
    "parameter-point": emit_parameter_point,
}

PENDING = {
    "merkle-leaf-encoding": "Task 2",
    "transcript-operations": "Task 2",
    "transcript-schedule": "Task 2",
    "air-constants": "Task 3",
    "deep-openings": "Task 3",
    "fri-layer-table": "Task 3",
    "hint-check": "Task 3",
    "verify-signature": "Task 4",
    "attest-integration": "Task 4",
    "soundness-accounting": "Task 4",
    "deviations-register": "Task 4",
    "vector-ctx": "Task 5",
    "vector-challenges": "Task 5",
    "vector-query-bundle": "Task 5",
    "vector-final": "Task 5",
    "wire-v1-appendix": "Task 5",
}


def render(block_id):
    if block_id in EMITTERS:
        return EMITTERS[block_id]()
    return ("Generated content for this block arrives in {} of the M3b"
            " plan; the fence is already owned by tools/gen_spec_tables.py"
            " and the CI drift gate.".format(PENDING[block_id]))


# ---------------- fence engine ----------------

def parse_fences(text):
    """Returns (lines, [(block_id, begin_idx, end_idx)]). Collects every
    violation before failing so one run reports all offenders."""
    lines = text.split("\n")
    fences, errors, seen = [], [], set()
    open_id, open_at = None, None
    for i, line in enumerate(lines):
        stripped = line.strip()
        m = FENCE_RE.match(stripped)
        if not m:
            if stripped.startswith("<!-- BEGIN-GENERATED") or \
                    stripped.startswith("<!-- END-GENERATED"):
                errors.append("line {}: malformed fence: {}".format(
                    i + 1, stripped))
            continue
        kind, bid = m.group(1), m.group(2)
        if kind == "BEGIN":
            if open_id is not None:
                errors.append("line {}: BEGIN {} inside open block {}"
                              .format(i + 1, bid, open_id))
            if bid in seen:
                errors.append("line {}: duplicate block id {}".format(
                    i + 1, bid))
            if bid not in EMITTERS and bid not in PENDING:
                errors.append("line {}: unknown block id {}".format(
                    i + 1, bid))
            open_id, open_at = bid, i
            seen.add(bid)
        else:
            if open_id is None:
                errors.append("line {}: END {} without BEGIN".format(
                    i + 1, bid))
            elif bid != open_id:
                errors.append("line {}: END {} does not match BEGIN {}"
                              .format(i + 1, bid, open_id))
                open_id, open_at = None, None
            else:
                fences.append((bid, open_at, i))
                open_id, open_at = None, None
    if open_id is not None:
        errors.append("BEGIN {} never closed".format(open_id))
    if errors:
        raise FenceError("fence validation failed:\n  "
                         + "\n  ".join(errors))
    return lines, fences


def splice(text):
    lines, fences = parse_fences(text)
    out, cursor = [], 0
    for bid, b, e in fences:
        out.extend(lines[cursor:b + 1])
        out.append(render(bid))
        cursor = e
    out.extend(lines[cursor:])
    return "\n".join(out), len(fences)


def main():
    text = read_text(SPEC)
    new, n = splice(text)
    if new != text:
        with open(SPEC, "w", encoding="utf-8") as f:
            f.write(new)
    print("gen_spec_tables: {} blocks regenerated".format(n))


if __name__ == "__main__":
    main()
