#!/usr/bin/env python3
"""gen_spec_tables.py: owns every generated block of docs/protocol-spec.md.

Splices deterministic content between HTML-comment fences:
    <!-- BEGIN-GENERATED: <block-id> -->
    <!-- END-GENERATED: <block-id> -->
Refuses to run when any BEGIN lacks its END, an id is unknown, or an id
repeats, listing every offender. Each block's content is read from a
named source (tools/params.py, tools/soundness.py, the production
contracts, tools/kats-full.json, docs/m3-testnet-receipts.md); this file
inlines no protocol value. Deterministic: no timestamps, no env reads.
Run:   python3 tools/gen_spec_tables.py     (regenerates the spec in place)
Tests: python3 tools/test_gen_spec_tables.py
"""
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SPEC = os.path.join(ROOT, "docs", "protocol-spec.md")
FLAT = os.path.join(ROOT, "contracts", "verifold-flat-full-production.clar")
QM31_GEAR = os.path.join(ROOT, "contracts", "full", "qm31.clar")

sys.path.insert(0, HERE)
import params  # noqa: E402

FENCE_RE = re.compile(r"^<!-- (BEGIN|END)-GENERATED: ([a-z0-9][a-z0-9-]*) -->$")


class FenceError(SystemExit):
    pass


def read_text(path):
    with open(path, "r", encoding="utf-8") as f:
        return f.read()


def contract_slice(text, start_anchor, end_anchor):
    """Lines from the unique line containing start_anchor up to but not
    including the first later line containing end_anchor. Asserts the
    start anchor is unique so silent drift is impossible."""
    lines = text.split("\n")
    starts = [i for i, l in enumerate(lines) if start_anchor in l]
    assert len(starts) == 1, (start_anchor, len(starts))
    ends = [i for i, l in enumerate(lines)
            if end_anchor in l and i > starts[0]]
    assert ends, end_anchor
    return "\n".join(lines[starts[0]:ends[0]]).rstrip()


def src_note(*sources):
    return ("<!-- generated by tools/gen_spec_tables.py from: "
            + "; ".join(sources) + " -->")


# ---------------- emitters (Task 1) ----------------

def emit_field_constants():
    p = params.P
    assert p == 2 ** 31 - 1, p
    return "\n".join([
        src_note("tools/params.py (P)"),
        "",
        "| constant | value | definition |",
        "| --- | --- | --- |",
        "| p | {} | the Mersenne prime 2^31 - 1; every base field value"
        " is an integer in [0, p) |".format(p),
    ])


def emit_qm31_tower():
    hdr = read_text(QM31_GEAR)

    def header_line(marker):
        for line in hdr.split("\n"):
            if marker in line:
                assert line.startswith(";;"), line
                # normalize whitespace; drop the gear comment tail after
                # the double-hyphen separator (the spec bans dash prose)
                return " ".join(line[2:].split()).split(" -- ")[0].strip()
        raise AssertionError("qm31.clar header drifted: " + marker)

    return "\n".join([
        src_note("contracts/full/qm31.clar (header: tower polynomials"
                 " and element shape)"),
        "",
        "```text",
        header_line("CM31 = M31[i]"),
        header_line("QM31 = CM31[u]"),
        header_line("An element {c0,c1,c2,c3} means"),
        "```",
    ])


def emit_circle_generator():
    gx, gy = params.G
    assert params.order_is(params.G, 2 ** 31), "G must have order 2^31"
    return "\n".join([
        src_note("tools/params.py (G, order verified via order_is)"),
        "",
        "| constant | value |",
        "| --- | --- |",
        "| G.x | {} |".format(gx),
        "| G.y | {} |".format(gy),
        "| order of G | 2^31, re-verified by params.order_is on every"
        " generation run |",
    ])


def emit_parameter_point():
    pt = params.PRODUCTION_POINT
    d = params.derived(pt)
    free = [("log_trace", pt["log_trace"]), ("log_blowup", pt["log_blowup"]),
            ("n_queries", pt["n_queries"]), ("pow_bits", pt["pow_bits"]),
            ("air_id", pt["air_id"])]
    der = [
        ("LOG_DOMAIN", d["LOG_DOMAIN"]), ("DOMAIN_SIZE", d["DOMAIN_SIZE"]),
        ("N_LAYERS", d["N_LAYERS"]), ("BLOWUP", d["BLOWUP"]),
        ("TRACE_ROWS", d["TRACE_ROWS"]),
        ("OFF", "re {re}, im {im}".format(**d["OFF"])),
        ("H", "re {re}, im {im}".format(**d["H"])),
        ("SX", d["SX"]), ("SY", d["SY"]),
        ("SEL", "A {A}, B {B}, C {C}".format(**d["SEL"])),
        ("B01", "A {A}, B {B}, C {C}".format(**d["B01"])),
        ("POW_THRESHOLD", d["POW_THRESHOLD"]),
        ("PARAMS (8 bytes, hex)", d["PARAMS"].hex()),
    ]
    out = [src_note("tools/params.py (PRODUCTION_POINT, derived())"), "",
           "Free choice tuple (PRODUCTION_POINT):", "",
           "| name | value |", "| --- | --- |"]
    out += ["| {} | {} |".format(k, v) for k, v in free]
    out += ["", "Derived constants at this point:", "",
            "| name | value |", "| --- | --- |"]
    out += ["| {} | {} |".format(k, v) for k, v in der]
    return "\n".join(out)


def emit_merkle_leaf_encoding():
    import hashlib
    flat = read_text(FLAT)
    code = contract_slice(flat, "(define-private (commit/m31-to-be4",
                          "(define-read-only (commit/opening-bound")
    assert "commit/qm31-enc16" in code and "commit/qm31-leaf" in code
    example = (1, 2, 3, 4)
    enc = b"".join(v.to_bytes(4, "big") for v in example)
    leaf = hashlib.sha256(enc).hexdigest()
    return "\n".join([
        src_note("contracts/verifold-flat-full-production.clar"
                 " (commit gear: m31-to-be4, qm31-enc16, qm31-leaf)"),
        "",
        "```clarity",
        code,
        "```",
        "",
        "Worked example, computed by the generator under the same"
        " convention (the contract KATs in the frozen test surface pin"
        " the contract to these bytes):",
        "",
        "| step | value |",
        "| --- | --- |",
        "| element | c0 {}, c1 {}, c2 {}, c3 {} |".format(*example),
        "| enc16 | {} |".format(enc.hex()),
        "| leaf = sha256(enc16) | {} |".format(leaf),
    ])


def emit_transcript_operations():
    flat = read_text(FLAT)
    tags = {}
    for name in ("OP_ABSORB", "OP_SQUEEZE", "OP_POW",
                 "T_ROOT", "T_QM31", "T_NONCE"):
        m = re.search(r"\(define-constant transcript/" + name
                      + r" (0x[0-9a-f]+)\)", flat)
        assert m, name
        tags[name] = m.group(1)
    ops = contract_slice(flat, "(define-read-only (transcript/transcript-init",
                         "(define-private (transcript/absorb-root-step")
    sqz = contract_slice(flat, "(define-private (transcript/read-u128-be",
                         ";; ========================= gear: schedule")
    meanings = [
        ("OP_ABSORB", "first byte after the state on every absorb"),
        ("OP_SQUEEZE", "the single byte appended to the state on every"
                       " squeeze"),
        ("OP_POW", "first byte after the state on the proof of work"
                   " check"),
        ("T_ROOT", "absorb type tag for a 32 byte Merkle root"),
        ("T_QM31", "absorb type tag for a 16 byte QM31 encoding"),
        ("T_NONCE", "absorb type tag for the 8 byte nonce"),
    ]
    out = [src_note("contracts/verifold-flat-full-production.clar"
                    " (transcript gear: op tag constants and the"
                    " absorb/squeeze/pow definitions)"), "",
           "| tag | byte | role |", "| --- | --- | --- |"]
    out += ["| {} | {} | {} |".format(n, tags[n], m) for n, m in meanings]
    out += ["", "```clarity", ops, "", sqz, "```"]
    return "\n".join(out)


def emit_transcript_schedule():
    import json
    flat = read_text(FLAT)
    n = int(re.search(r"\(define-constant schedule/N u(\d+)\)",
                      flat).group(1))
    l = int(re.search(r"\(define-constant schedule/L u(\d+)\)",
                      flat).group(1))
    dom = int(re.search(r"\(define-constant schedule/DOMAIN_SIZE u(\d+)\)",
                        flat).group(1))
    code = contract_slice(flat,
                          "(define-read-only (schedule/derive-challenges",
                          "(define-read-only (schedule/get-params")
    # cross-check the schedule shape against the committed KAT export
    with open(os.path.join(HERE, "kats-full.json")) as f:
        kats = json.load(f)
    assert len(kats["friRoots"]) == l and len(kats["betas"]) == l
    assert len(kats["queryIndices"]) == n
    for key in ("ctx", "traceRoot", "compRoot", "alpha", "zfelt", "Tz",
                "Tgz", "Tg2z", "Czs", "gamma", "final", "nonce"):
        assert key in kats, key
    steps = [
        "init: state = sha256(ctx)",
        "absorb T_ROOT trace root, then squeeze one QM31: alpha",
        "absorb T_ROOT composition root, then squeeze one QM31: z",
        "absorb T_QM31 seven times, in order t(z), t(gz), t(g^2 z),"
        " c0(z), c1(z), c2(z), c3(z), with no squeeze between them",
        "squeeze one QM31: gamma",
        "for each of the {} FRI roots in layer order: absorb T_ROOT the"
        " root, then squeeze one QM31: beta of that layer".format(l),
        "absorb T_QM31 the transmitted final value",
        "proof of work check on the current state with the 8 byte nonce"
        " (reads the state, does not advance it)",
        "absorb T_NONCE the nonce",
        "squeeze m31 {} times; each query index is the squeezed value"
        " mod {}".format(n, dom),
    ]
    out = [src_note("contracts/verifold-flat-full-production.clar"
                    " (schedule gear: constants and derive-challenges);"
                    " cross-checked against tools/kats-full.json"), "",
           "| step | operation |", "| --- | --- |"]
    out += ["| {} | {} |".format(i + 1, s) for i, s in enumerate(steps)]
    out += ["", "The normative definition, verbatim:", "",
            "```clarity", code, "```"]
    return "\n".join(out)


def emit_air_constants():
    d = params.derived(params.PRODUCTION_POINT)
    flat = read_text(FLAT)
    cair = {}
    for name in ("SX", "SY", "SEL_A", "SEL_B", "SEL_C",
                 "B01_A", "B01_B", "B01_C"):
        m = re.search(r"\(define-constant cair/" + name + r" u(\d+)\)",
                      flat)
        assert m, name
        cair[name] = int(m.group(1))
    # the contract constants must equal the math recomputed by params.py
    assert (cair["SX"], cair["SY"]) == (d["SX"], d["SY"])
    assert (cair["SEL_A"], cair["SEL_B"], cair["SEL_C"]) == \
        (d["SEL"]["A"], d["SEL"]["B"], d["SEL"]["C"])
    assert (cair["B01_A"], cair["B01_B"], cair["B01_C"]) == \
        (d["B01"]["A"], d["B01"]["B"], d["B01"]["C"])
    # air_id registry rows from params.POINTS (id -> point names)
    by_id = {}
    for name in sorted(params.POINTS):
        by_id.setdefault(params.POINTS[name]["air_id"], []).append(name)
    # the registry rule, quoted from the params.py source comment
    psrc = read_text(os.path.join(HERE, "params.py"))
    rule = [" ".join(l[1:].split()) for l in psrc.split("\n")
            if l.startswith("#") and ("air_id registry is monotonic" in l
                                      or "production-trace circle" in l
                                      or "never reuse a retired id" in l)]
    assert rule, "params.py registry comment drifted"
    out = [src_note("tools/params.py (derived() SEL/B01, POINTS, the"
                    " registry comment); cross-checked against the cair"
                    " constants in contracts/"
                    "verifold-flat-full-production.clar"), "",
           "Selector and boundary lines (A*x + B*y + C, M31"
           " coefficients), equal in params.py and the contract:", "",
           "| line | A | B | C | vanishes on |", "| --- | --- | --- |"
           " --- | --- |",
           "| SEL | {A} | {B} | {C} | the last two trace coset points |"
           .format(**d["SEL"]),
           "| B01 | {A} | {B} | {C} | the first two trace coset points |"
           .format(**d["B01"]),
           "", "Trace step (S = generator of the trace coset walk):", "",
           "| constant | value |", "| --- | --- |",
           "| SX | {} |".format(d["SX"]),
           "| SY | {} |".format(d["SY"]),
           "", "air_id registry (from params.POINTS):", "",
           "| air_id | parameter points carrying it |", "| --- | --- |"]
    out += ["| {} | {} |".format(k, ", ".join(v))
            for k, v in sorted(by_id.items())]
    out += ["", "Registry rule, quoted from tools/params.py:", "",
            "```text"] + rule + ["```"]
    return "\n".join(out)


def emit_deep_openings():
    flat = read_text(FLAT)
    helpers = contract_slice(flat,
                             "(define-read-only (cdeep/line-coeffs",
                             "(define-private (cdeep/rot-s")
    deep = contract_slice(flat, "(define-read-only (cdeep/deep-row",
                          ";; ========================= gear: merkle")
    rows = [
        ("t(z)", "1 (gamma^0)", "(cdeep/line-coeffs zy t-z one)"),
        ("t(gz)", "gamma", "(cdeep/line-coeffs (get y z1) t-gz gamma)"),
        ("t(g^2 z)", "gamma^2",
         "(cdeep/line-coeffs (get y z2) t-g2z g2)"),
        ("c0(z)", "gamma^3", "(cdeep/line-coeffs zy c0-z g3)"),
        ("c1(z)", "gamma^4", "(cdeep/line-coeffs zy c1-z g4)"),
        ("c2(z)", "gamma^5", "(cdeep/line-coeffs zy c2-z g5)"),
        ("c3(z)", "gamma^6", "(cdeep/line-coeffs zy c3-z g6)"),
    ]
    for _, _, anchor in rows:
        assert anchor in deep, anchor  # a weight reshuffle fails loudly
    out = [src_note("contracts/verifold-flat-full-production.clar"
                    " (cdeep gear: line-coeffs, denom-inv, quot-term,"
                    " deep-row); each table row's weight is re-verified"
                    " against the deep-row source on every run"), "",
           "| opening | gamma weight | contract anchor |",
           "| --- | --- | --- |"]
    out += ["| {} | {} | `{}` |".format(*r) for r in rows]
    out += ["", "```clarity", helpers, "", deep, "```"]
    return "\n".join(out)


def emit_fri_layer_table():
    d = params.derived(params.PRODUCTION_POINT)
    flat = read_text(FLAT)
    n_layers, dom = d["N_LAYERS"], d["DOMAIN_SIZE"]
    # cross-checks: the contract carries exactly these layer counts
    l = int(re.search(r"\(define-constant schedule/L u(\d+)\)",
                      flat).group(1))
    assert l == n_layers, (l, n_layers)
    line_xs = re.findall(r"\(define-read-only \(driver/line-x(\d+) ",
                         flat)
    assert sorted(int(x) for x in line_xs) == \
        list(range(1, n_layers)), line_xs
    rows = [("0", dom, "committed (fri root 0)",
             "circle: y of the even paired query point")]
    for k in range(1, n_layers):
        rows.append((str(k), dom >> k,
                     "committed (fri root {})".format(k),
                     "line: pi applied {} times to the layer base x"
                     .format(k - 1)))
    rows.append((str(n_layers), dom >> n_layers,
                 "transmitted degree 0 final value, compared per query,"
                 " never committed", "none"))
    out = [src_note("tools/params.py (derived() N_LAYERS, DOMAIN_SIZE);"
                    " cross-checked against schedule/L and the"
                    " driver/line-x ladder in contracts/"
                    "verifold-flat-full-production.clar"), "",
           "| layer | size | committed or transmitted | twiddle |",
           "| --- | --- | --- | --- |"]
    out += ["| {} | {} | {} | {} |".format(*r) for r in rows]
    return "\n".join(out)


def emit_hint_check():
    flat = read_text(FLAT)
    code = contract_slice(flat,
                          "(define-read-only (fri/fri-fold-step-hint",
                          "(define-private (fri/fold-layer-step-hint")
    guard = ("(unwrap-panic (if (is-eq (field/m31-mul x hint) u1)"
             " (some true) none))")
    assert guard in code, "hint guard drifted"
    return "\n".join([
        src_note("contracts/verifold-flat-full-production.clar"
                 " (fri gear: fri-fold-step-hint; the guard line is"
                 " re-verified verbatim on every run)"), "",
        "The wire v2 inverse hint check, verbatim:", "",
        "```clarity", code, "```", "",
        "The guard line an independent implementation must reproduce"
        " exactly:", "",
        "```clarity", guard, "```",
    ])


def emit_verify_signature():
    flat = read_text(FLAT)
    sig = contract_slice(flat, "(define-read-only (driver/verify",
                         "(let ((params (schedule/get-params))")
    names = re.findall(r"^    \((\S+) ", sig, flags=re.M)
    expected = ["pub", "trace-root", "comp-root", "t-z", "t-gz",
                "t-g2z", "c0-z", "c1-z", "c2-z", "c3-z", "fri-roots",
                "final", "nonce", "queries"]
    assert names == expected, names
    qm31 = "QM31 tuple { c0, c1, c2, c3: uint }"
    kinds = {
        "pub": "(buff 256): public input bytes; the statement binds"
               " sha256(pub) through ctx",
        "trace-root": "(buff 32): Merkle root of the trace column",
        "comp-root": "(buff 32): Merkle root of the four composition"
                     " columns",
        "t-z": qm31 + ": trace opened at z",
        "t-gz": qm31 + ": trace opened at gz",
        "t-g2z": qm31 + ": trace opened at g^2 z",
        "c0-z": qm31 + ": composition column 0 opened at z",
        "c1-z": qm31 + ": composition column 1 opened at z",
        "c2-z": qm31 + ": composition column 2 opened at z",
        "c3-z": qm31 + ": composition column 3 opened at z",
        "fri-roots": "(list 16 (buff 32)): the committed FRI layer"
                     " roots, layer order",
        "final": qm31 + ": the transmitted degree 0 final value",
        "nonce": "(buff 8): the proof of work nonce",
        "queries": "(list 23 ...): one decommitment bundle per drawn"
                   " query; the full tuple shape is in the listing",
    }
    out = [src_note("contracts/verifold-flat-full-production.clar"
                    " (driver/verify signature, sliced between verified"
                    " anchors; the 14 name table is parsed from the"
                    " slice on every run)"), "",
           "| # | parameter | type and meaning |", "| --- | --- | --- |"]
    out += ["| {} | {} | {} |".format(i + 1, n, kinds[n])
            for i, n in enumerate(names)]
    out += ["", "```clarity", sig, "```"]
    return "\n".join(out)


ATTEST = os.path.join(ROOT, "contracts", "verifold-attest.clar")
RECEIPTS = os.path.join(ROOT, "docs", "m3-testnet-receipts.md")


def emit_attest_integration():
    attest = read_text(ATTEST)
    idx = attest.index("(define-public (attest")
    code = attest[idx:].rstrip("\n")
    assert ("contract-call? .verifold-flat-full-production"
            " driver/verify") in code
    receipts = read_text(RECEIPTS)
    deployer = re.search(r"Deployer: (ST[0-9A-Z]+)", receipts).group(1)
    verifier_id = deployer + ".verifold-flat-full-production"
    attest_id = deployer + ".verifold-attest"
    assert "### " + verifier_id in receipts, verifier_id
    assert "### " + attest_id in receipts, attest_id
    m = re.search(r"verifold-flat-full-production\n(?:.*\n)*?"
                  r"- Tx status: success, block height (\d+)", receipts)
    assert m, "deploy block not found in receipts"
    block = m.group(1)
    out = [src_note("contracts/verifold-attest.clar (the attest entry"
                    " point, verbatim); docs/m3-testnet-receipts.md"
                    " (live identifiers, parsed at run time)"), "",
           "| identifier | value |", "| --- | --- |",
           "| deployer | {} |".format(deployer),
           "| verifier contract | {} |".format(verifier_id),
           "| consumer contract | {} |".format(attest_id),
           "| deploy block | {} |".format(block),
           "| receipts | docs/m3-testnet-receipts.md |",
           "", "```clarity", code, "```"]
    return "\n".join(out)


def emit_soundness_accounting():
    import soundness
    pt = params.PRODUCTION_POINT
    b = soundness.bits(pt)
    t = b["terms"]
    return "\n".join([
        src_note("tools/soundness.py bits(PRODUCTION_POINT);"
                 " tools/params.py (the point values)"), "",
        "| term | bits | derivation |", "| --- | --- | --- |",
        "| query_term | {} | n_queries * log_blowup = {} * {} |".format(
            t["query_term"], pt["n_queries"], pt["log_blowup"]),
        "| proven_query_term | {} | query_term / 2, the Johnson bound"
        " halving |".format(t["proven_query_term"]),
        "| grinding_term | {} | pow_bits |".format(t["grinding_term"]),
        "| ood_term | {} | 4 * log2(p), the QM31 challenge space"
        " ceiling |".format(t["ood_term"]),
        "| transcript_term | {} | the 16 byte sha256 read ceiling |"
        .format(t["transcript_term"]),
        "| applied_cap | {} | both additive sums sit below both"
        " ceilings |".format(t["applied_cap"]),
        "",
        "Headline, conjectured (UNPROVEN; ethSTARK Conjecture 1 style"
        " capacity accounting, IACR ePrint 2021/582): {} bits ="
        " query_term + grinding_term. The proven companion below is"
        " {} bits.".format(b["conjectured"], b["proven"]),
        "",
        "Headline, proven (Johnson bound): {} bits = proven_query_term"
        " + grinding_term.".format(b["proven"]),
    ])


DEVIATIONS = [
    ("untagged leaf hash",
     "a Merkle leaf is sha256 of the 16 byte QM31 encoding with no"
     " leaf tag byte",
     "contracts/full/commit.clar", "Leaf is UNTAGGED sha256(16B)",
     "docs/expert-review-questions.md item 10 and DRIVER-1"),
    ("no leaf/node domain separation",
     "an interior node is sha256 of the two child hashes with no node"
     " tag byte",
     "contracts/full/commit.clar",
     "leaf/node domain separation is a DOCUMENTED DEFAULT",
     "docs/expert-review-questions.md item 10 and CAIR-2"),
    ("drawn, not deduplicated, query indices",
     "the 23 query indices are drawn independently and never"
     " deduplicated",
     "contracts/full/schedule.clar", "query-idx-step",
     "docs/expert-review-questions.md DRIVER-3 and CAIR-7; quantified"
     " in docs/m2-soundness.md"),
    ("squeeze reduction bias",
     "challenges reduce 16 big endian sha256 bytes mod p, total"
     " variation bias about 2^-124",
     "contracts/full/transcript.clar", "bias ~2^-124",
     "docs/expert-review-questions.md item 8"),
    ("minimum, not error sum, soundness cap",
     "the soundness ceilings combine as a minimum rather than an error"
     " sum",
     "tools/soundness.py", "cap = min(ood_term, transcript_term)",
     "docs/expert-review-questions.md item 3 and DRIVER-9; quantified"
     " in docs/m2-soundness.md"),
    ("query index modulus",
     "each drawn index is the squeezed m31 value reduced mod"
     " DOMAIN_SIZE",
     "contracts/full/schedule.clar", "DOCUMENTED DEFAULT",
     "docs/expert-review-questions.md QUERY-5 and DRIVER-3"),
    ("sha256 duplex transcript",
     "the whole Fiat-Shamir construction is a single digest sha256"
     " duplex with 1 byte op tags",
     "contracts/full/transcript.clar", "Design (locked",
     "docs/expert-review-questions.md item 5 and CAIR-6"),
    ("circle domain conventions",
     "coset offset, bit reversal direction, first fold twiddle, and"
     " mask shift semantics follow Stwo as read; empirically cross"
     " checked by the gear 6f interop harness, still awaiting expert"
     " blessing",
     "contracts/full/query.clar",
     "documented defaults matching Stwo's source",
     "docs/expert-review-questions.md QUERY-1 to QUERY-6"),
]


def emit_deviations_register():
    out = [src_note("the hand maintained DEVIATIONS list in"
                    " tools/gen_spec_tables.py; every source anchor is"
                    " re-verified against its file on every run"), "",
           "| # | default | where it lives | tracked by |",
           "| --- | --- | --- | --- |"]
    for i, (name, what, where, anchor, tracker) in enumerate(
            DEVIATIONS, 1):
        assert anchor in read_text(os.path.join(ROOT, where)), \
            (name, where, anchor)
        out.append("| {} | {}: {} | {} | {} |".format(
            i, name, what, where, tracker))
    return "\n".join(out)


EMITTERS = {
    "field-constants": emit_field_constants,
    "qm31-tower": emit_qm31_tower,
    "circle-generator": emit_circle_generator,
    "parameter-point": emit_parameter_point,
    "merkle-leaf-encoding": emit_merkle_leaf_encoding,
    "transcript-operations": emit_transcript_operations,
    "transcript-schedule": emit_transcript_schedule,
    "air-constants": emit_air_constants,
    "deep-openings": emit_deep_openings,
    "fri-layer-table": emit_fri_layer_table,
    "hint-check": emit_hint_check,
    "verify-signature": emit_verify_signature,
    "attest-integration": emit_attest_integration,
    "soundness-accounting": emit_soundness_accounting,
    "deviations-register": emit_deviations_register,
}

PENDING = {
    "vector-ctx": "Task 5",
    "vector-challenges": "Task 5",
    "vector-query-bundle": "Task 5",
    "vector-final": "Task 5",
    "wire-v1-appendix": "Task 5",
}


def render(block_id):
    if block_id in EMITTERS:
        return EMITTERS[block_id]()
    return ("Generated content for this block arrives in {} of the M3b"
            " plan; the fence is already owned by tools/gen_spec_tables.py"
            " and the CI drift gate.".format(PENDING[block_id]))


# ---------------- fence engine ----------------

def parse_fences(text):
    """Returns (lines, [(block_id, begin_idx, end_idx)]). Collects every
    violation before failing so one run reports all offenders."""
    lines = text.split("\n")
    fences, errors, seen = [], [], set()
    open_id, open_at = None, None
    for i, line in enumerate(lines):
        stripped = line.strip()
        m = FENCE_RE.match(stripped)
        if not m:
            if stripped.startswith("<!-- BEGIN-GENERATED") or \
                    stripped.startswith("<!-- END-GENERATED"):
                errors.append("line {}: malformed fence: {}".format(
                    i + 1, stripped))
            continue
        kind, bid = m.group(1), m.group(2)
        if kind == "BEGIN":
            if open_id is not None:
                errors.append("line {}: BEGIN {} inside open block {}"
                              .format(i + 1, bid, open_id))
            if bid in seen:
                errors.append("line {}: duplicate block id {}".format(
                    i + 1, bid))
            if bid not in EMITTERS and bid not in PENDING:
                errors.append("line {}: unknown block id {}".format(
                    i + 1, bid))
            open_id, open_at = bid, i
            seen.add(bid)
        else:
            if open_id is None:
                errors.append("line {}: END {} without BEGIN".format(
                    i + 1, bid))
            elif bid != open_id:
                errors.append("line {}: END {} does not match BEGIN {}"
                              .format(i + 1, bid, open_id))
                open_id, open_at = None, None
            else:
                fences.append((bid, open_at, i))
                open_id, open_at = None, None
    if open_id is not None:
        errors.append("BEGIN {} never closed".format(open_id))
    if errors:
        raise FenceError("fence validation failed:\n  "
                         + "\n  ".join(errors))
    return lines, fences


def splice(text):
    lines, fences = parse_fences(text)
    out, cursor = [], 0
    for bid, b, e in fences:
        out.extend(lines[cursor:b + 1])
        out.append(render(bid))
        cursor = e
    out.extend(lines[cursor:])
    return "\n".join(out), len(fences)


def main():
    text = read_text(SPEC)
    new, n = splice(text)
    if new != text:
        with open(SPEC, "w", encoding="utf-8") as f:
            f.write(new)
    print("gen_spec_tables: {} blocks regenerated".format(n))


if __name__ == "__main__":
    main()
