#!/usr/bin/env python3
# The scale-up measurement spike: does a full-security-parameter verify fit one transaction?
#
# Generates a FLATTENED single-contract Clarity program whose execution shape matches the
# full-security verifier: per query, the right number of sha256 Merkle levels at real tree depths,
# the live-DEEP field-work (qm31 multiplies, hint-checked inverses), the fold chain, plus the
# one-off Fiat-Shamir schedule. Values are synthetic (sha256 chains stand in for siblings; cost
# does not depend on values), correctness is NOT computed -- this measures COST SHAPE only.
#
# Conventions measured against (the things that make this representative):
#   - one private function per field op, with the arithmetic INLINE in its body (no nested helper
#     pyramid, no cross-contract dispatch) -- the "flattening codegen" architecture;
#   - inverses via PROVER HINTS (one multiply + equality instead of 31-step Fermat);
#   - per-query work in ONE shared private function applied Q times.
#
# Usage: python3 tools/gen_fullsize.py <depth> <queries> > contracts/fullsize.clar
import sys

D = int(sys.argv[1]) if len(sys.argv) > 1 else 17  # log2(LDE domain): trees are depth D
Q = int(sys.argv[2]) if len(sys.argv) > 2 else 70  # query count
L = D - 1                                          # fold layers (circle + lines, to a size-2 last layer)

out = []
emit = out.append
emit(f";; AUTO-GENERATED cost-shape prototype: depth {D} trees, {Q} queries, {L} fold layers.")
emit(";; Generated by tools/gen_fullsize.py. A cost-shape measurement artifact, NOT a real verifier.")
emit("(define-constant P u2147483647)")

# ---- inline field ops (one application level; bodies are pure expressions) ----
emit("""
(define-private (mm (a uint) (b uint)) (mod (* a b) P))
(define-private (ma (a uint) (b uint)) (mod (+ a b) P))
(define-private (ms (a uint) (b uint)) (mod (- (+ a P) b) P))
;; qm31 multiply with the tower arithmetic written out inline (12 base muls + combinations)
(define-private (qmul (a (list 4 uint)) (b (list 4 uint)))
  (let ((a0 (unwrap-panic (element-at? a u0))) (a1 (unwrap-panic (element-at? a u1)))
        (a2 (unwrap-panic (element-at? a u2))) (a3 (unwrap-panic (element-at? a u3)))
        (b0 (unwrap-panic (element-at? b u0))) (b1 (unwrap-panic (element-at? b u1)))
        (b2 (unwrap-panic (element-at? b u2))) (b3 (unwrap-panic (element-at? b u3)))
        (ac0 (ms (mm a0 b0) (mm a1 b1))) (ac1 (ma (mm a0 b1) (mm a1 b0)))
        (bd0 (ms (mm a2 b2) (mm a3 b3))) (bd1 (ma (mm a2 b3) (mm a3 b2)))
        (ad0 (ms (mm a0 b2) (mm a1 b3))) (ad1 (ma (mm a0 b3) (mm a1 b2)))
        (bc0 (ms (mm a2 b0) (mm a3 b1))) (bc1 (ma (mm a2 b1) (mm a3 b0)))
        (r0 (ms (ma bd0 bd0) bd1)) (r1 (ma bd0 (ma bd1 bd1))))
    (list (ma ac0 r0) (ma ac1 r1) (ma ad0 bc0) (ma ad1 bc1))))
(define-private (qadd (a (list 4 uint)) (b (list 4 uint)))
  (list (ma (unwrap-panic (element-at? a u0)) (unwrap-panic (element-at? b u0)))
        (ma (unwrap-panic (element-at? a u1)) (unwrap-panic (element-at? b u1)))
        (ma (unwrap-panic (element-at? a u2)) (unwrap-panic (element-at? b u2)))
        (ma (unwrap-panic (element-at? a u3)) (unwrap-panic (element-at? b u3)))))
(define-private (qmulm (a (list 4 uint)) (s uint))
  (list (mm (unwrap-panic (element-at? a u0)) s) (mm (unwrap-panic (element-at? a u1)) s)
        (mm (unwrap-panic (element-at? a u2)) s) (mm (unwrap-panic (element-at? a u3)) s)))
;; hint-checked inverse WORK SHAPE: one qmul + one equality. (The real verifier aborts on a bad
;; hint; here values are synthetic, so the same operations run but the branch returns either way.)
(define-private (qinv-hint (v (list 4 uint)) (hint (list 4 uint)))
  (if (is-eq (qmul v hint) (list u1 u0 u0 u0)) hint hint))
""")

# ---- a depth-N climb as ONE let with sequential bindings (sha256 chains synthesize siblings) ----
def climb_fn(name, depth):
    lines = [f"(define-private ({name} (leaf (buff 32)) (seed (buff 32)))", "  (let ("]
    prev_h, prev_s = "leaf", "seed"
    for i in range(depth):
        lines.append(f"    (s{i} (sha256 {prev_s}))")
        lines.append(f"    (h{i} (sha256 (concat {prev_h} s{i})))")
        prev_h, prev_s = f"h{i}", f"s{i}"
    lines.append(f"  ) {prev_h}))")
    return "\n".join(lines)

emit(climb_fn("climb-full", D))          # trace/comp full-depth climbs
for ell in range(1, L):                   # inner-layer parent paths: depth D-ell-1
    d = D - ell - 1
    if d > 0:
        emit(climb_fn(f"climb-l{ell}", d))

# ---- the per-query pipeline ----
lines = ["(define-private (do-query (seed (buff 32)))", "  (let ("]
b = lambda i: f"q{i}"
# synthesize a few qm31 values from the seed (cheap; outside the measured hot path's character)
lines.append("    (v0 (list (mod (buff-to-uint-be (unwrap-panic (as-max-len? (unwrap-panic (slice? seed u0 u4)) u4))) P) u3 u5 u7))")
lines.append("    (v1 (list u11 u13 u17 u19)) (v2 (list u23 u29 u31 u37)) (hint (list u41 u43 u47 u53))")
# 1+2: trace + comp climbs (leaf hashes + full-depth paths)
lines.append("    (tl (sha256 seed)) (cl (sha256 tl))")
lines.append("    (tr (climb-full tl seed)) (cr (climb-full cl tr))")
# 3: deep-row field work: gamma powers (6), ~60 qmul + ~12 qmulm + ~30 qadd + 3 hinted inverses
acc = "v0"
n = 0
for i in range(6):                       # gamma powers
    lines.append(f"    (g{i} (qmul {acc} v1))"); acc = f"g{i}"; n += 1
for i in range(54):                      # line coeffs + numerator terms across 3 batches
    lines.append(f"    (d{i} (qmul {acc} v2))"); acc = f"d{i}"
for i in range(12):
    lines.append(f"    (e{i} (qmulm {acc} u9973))"); acc = f"e{i}"
for i in range(30):
    lines.append(f"    (f{i} (qadd {acc} v1))"); acc = f"f{i}"
for i in range(3):                       # CM31 denominator inverses, hint-checked
    lines.append(f"    (dn{i} (qmul {acc} (qinv-hint v2 hint)))"); acc = f"dn{i}"
# 4: query-point derivation: ~2*D cm-muls ~= D qmul-equivalents, + L pi-iterations (m31 muls)
for i in range(D):
    lines.append(f"    (p{i} (qmul {acc} v1))"); acc = f"p{i}"
# 5: first-layer pair bind (2 leaves + pair + depth D-1 path) and the fold chain with per-layer
#    inner binds (leaf x2 + pair + parent path) and hinted twiddle inverses
lines.append(f"    (fl0 (sha256 (concat (sha256 seed) (sha256 tr))))")
lines.append(f"    (fb0 (climb-l1 fl0 seed))" if L > 1 else "    (fb0 fl0)")
for ell in range(1, L):
    d = D - ell - 1
    lines.append(f"    (lf{ell} (sha256 (concat (sha256 fb{ell-1}) (sha256 seed))))")
    if d > 0:
        lines.append(f"    (fb{ell} (climb-l{ell} lf{ell} fb{ell-1}))")
    else:
        lines.append(f"    (fb{ell} lf{ell})")
    # the fold step: (a+b) + beta*(a-b)*twiddle_inv  ~= 1 qmul + 1 qmulm + 2 qadd + hint mul
    lines.append(f"    (fv{ell} (qadd (qmul {acc} v1) (qmulm (qinv-hint v2 hint) u8191)))"); acc = f"fv{ell}"
lines.append(f"  ) (sha256 (concat fb{L-1} (sha256 seed)))))")
emit("\n".join(lines))

# ---- the one-off schedule shape (~150 sha256: absorbs, squeezes, betas, pow, draws) ----
lines = ["(define-private (do-schedule (seed (buff 32)))", "  (let ("]
prev = "seed"
for i in range(150):
    lines.append(f"    (t{i} (sha256 {prev}))"); prev = f"t{i}"
lines.append(f"  ) {prev}))")
emit("\n".join(lines))

# ---- top level: schedule once + Q queries via fold ----
seeds = " ".join(f"0x{i:064x}" for i in range(Q))
emit(f"""
(define-private (query-step (s (buff 32)) (acc (buff 32)))
  (sha256 (concat acc (do-query s))))
(define-read-only (run)
  (fold query-step (list {seeds}) (do-schedule 0x{0:064x})))
""")

sys.stdout.write("\n".join(out) + "\n")
